//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisasMinerSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisasMinerSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartGTX 960Mgap=2,-l=T20x5EndGTX 960M
        ///
        ///StartGTX 970gap=2,-l=T13x20EndGTX 970
        ///
        ///
        ///StartGTX 1080 Tigap=3,-l=T55x20EndGTX 1080 Ti
        ///
        ///StartGTX 1080gap=3,-l=T39x10EndGTX 1080
        ///
        ///StartGTX 1070 Tigap=2,-l=T37x20EndGTX 1070 Ti
        ///
        ///StartGTX 1050 Tigap=2,-l=AutoEndGTX 1050 Ti
        ///
        ///StartGTX 1070gap=2,-l=T29x20EndGTX 1070
        ///
        ///StartGTX 1060gap=2,-l=T30x20EndGTX 1060
        ///
        ///StartRX 480 Graphicsgap=2,I=20EndRX 480 Graphics
        ///
        ///
        ///.
        /// </summary>
        internal static string GPUList {
            get {
                return ResourceManager.GetString("GPUList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Myicon {
            get {
                object obj = ResourceManager.GetObject("Myicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
